### ISSUE TITLE
runner.sh vs MNIST-runner.sh

### ISSUE THREAD

**Issue by dathath** [matthewwicker/ProbabilisticSafetyforBNNs#1]
Hello,

Thanks for sharing the code for your paper. I was trying to understand the codebase, and I was going through the code for the MNIST experiments -- to reproduce the paper results, should I be running runner.sh or MNIST-runner.sh? Also, what does setting margin to 0.0 do?

**Comment by matthewwicker** [comment]
Hi Sumanth,

Thanks for the question! In principle you can run either as they will do different things. If you run MNIST-runner.sh you need to supply an argument to the script corresponding to the width of the BNN you want to verify ($1 in the bash script).  I see now that the script MNIST-runner.sh you will also need to uncomment out the bash for-loop and supply your own arguments in order to loop over the desired images. Whereas runner.sh just assumes you want to verify a BNN with width 256 over the given image range. I think just running runner.sh is a good starting point.

As for setting margin to 0.0 this will perform propagation with no weight margin which will enable you to get a statistical estimate of the robustness by taking the number of safe weight margins found divided by the number of samples taken. For margin = 0.0 the lower-bound probability will necessarily be 0. 

I hope this helps! Feel free to follow up with any questions you have.

Best,
Matthew

**Comment by dathath** [comment]
Is the for-loop comment in regard to concurMNIST2 or concurMNIST? (I couldn't find the commented for-loop)

'which will enable you to get a statistical estimate of the robustness' -- does the code already do this computation? Could you  please point me to  it?

Thanks a ton for the help here!

**Comment by matthewwicker** [comment]
In this case I was talking about concurMNIST. In concurMNIST2 the for-loop appears to be hard-coded. 

As for the statistical estimate, placing the following code after line 100 of concurMNIST2/IBP-MNIST-Verify.py will print it out. Code: print(“Statistical Estimate: “, len(valid_intervals)/iters) 
I think there is probably code somewhere which logs this, but it has been a long time since I have looked at this code base.

For an easier time verifying BNNs you might consider using some of the posteriors from our later paper in AISTATS2021 (http://proceedings.mlr.press/v130/wicker21a.html). Repository: https://github.com/matthewwicker/CertifiableBayesianInference

In addition, please feel free to reach out to me via email if you would like to set up a meeting to discuss anything in these papers. 

Of course, feel free to continue asking questions here and I will answer them as I see them :) 

Best,
Matthew

**Comment by matthewwicker** [comment]
I closed this issue as I guess the confusion about the usage of the files is cleared up now! But feel free to leave another comment if you need any further assistance :)

**Comment by dathath** [comment]
Thanks -- yes, my main question was regarding the usage! Is the right hyperparameter for margin the one in runner.sh?

**Comment by matthewwicker** [comment]
Hi, 

Looking at the logs on the server it appears that everything that was in concurMNIST2 was run with margin=2.0 and a sample number that varied based on network size with widths 128, 256, 512 we used sample sizes 1000, 1500, and 1750 respectively. 

Edit: Whoops, I was wrong! I _did_ push the logs for this project. You can find them in the Depth2Logs directory. The hyper parameter selection is seen in all of the images with non-zero safety probability. Sorry, again it has been a long time since I handled this codebase.

Hope that helps!

Best,
Matthew
